import { CommonModule, DatePipe } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { catchError, forkJoin, of } from 'rxjs';
import { map } from 'rxjs/operators';
import {
  Grant, Organisation, OrganisationCategoryValues, OrganisationShareRequest, ShareCodeRedemptionView,
} from '../../models';
import { VaultApiService } from '../../services/vault-api.service';

interface SharedDataRow {
  categoryId: string;
  displayName: string;
  userId: string;
  fields: Array<{ label: string; value: string }>;
}

@Component({
  selector: 'app-organisation',
  standalone: true,
  imports: [CommonModule, FormsModule, DatePipe],
  templateUrl: './organisation.component.html',
  styleUrl: './organisation.component.css',
})
export class OrganisationComponent {
  private readonly api = inject(VaultApiService);
  private approvalPollId: number | null = null;

  readonly shareCode = signal('');
  readonly error = signal('');
  readonly statusMessage = signal('');
  readonly loading = signal(false);
  readonly orgQuery = signal('');
  readonly organisations = signal<Organisation[]>([]);
  readonly selectedOrganisationId = signal('');
  readonly selectedOrganisationName = signal('');
  readonly redemption = signal<ShareCodeRedemptionView | null>(null);
  readonly approvedRecords = signal<SharedDataRow[]>([]);
  readonly shareRequests = signal<OrganisationShareRequest[]>([]);
  readonly expandedCategoryIds = signal<ReadonlySet<string>>(new Set());

  readonly isAwaitingApproval = computed(() => this.redemption()?.status === 'AwaitingApproval');
  readonly unapprovedRequests = computed(() =>
    this.shareRequests().filter((r) => r.status === 'AwaitingApproval'),
  );

  constructor() {
    this.searchOrganisations();
  }

  private stopApprovalPolling(): void {
    if (this.approvalPollId !== null) {
      window.clearInterval(this.approvalPollId);
      this.approvalPollId = null;
    }
  }

  private beginApprovalPolling(userId: string): void {
    this.stopApprovalPolling();

    const poll = () => {
      this.loadShareRequests();

      this.api
        .listOrganisationGrants(this.selectedOrganisationId())
        .pipe(catchError(() => of([] as Grant[])))
        .subscribe((grants) => {
          const activeGrants = Array.isArray(grants) ? grants : [];

          if (!activeGrants.length) {
            return;
          }

          this.statusMessage.set('The user has approved this request. Live data is now visible below.');
          this.stopApprovalPolling();
          this.loadApprovedDataForOrganisation();
        });
    };

    poll();
    this.approvalPollId = window.setInterval(poll, 5000);
  }

  searchOrganisations(): void {
    this.api
      .searchOrganisations(this.orgQuery())
      .pipe(catchError(() => of([] as Organisation[])))
      .subscribe((orgs) => {
        this.organisations.set(orgs);

        if (!this.selectedOrganisationId() && orgs.length) {
          const primaryOrg = orgs[0];
          this.selectedOrganisationId.set(primaryOrg.id);
          this.selectedOrganisationName.set(primaryOrg.name);
        }

        if (this.selectedOrganisationId()) {
          this.loadApprovedDataForOrganisation();
          this.loadShareRequests();
        }
      });
  }

  toggleExpanded(categoryId: string): void {
    const expanded = new Set(this.expandedCategoryIds());
    if (expanded.has(categoryId)) {
      expanded.delete(categoryId);
    } else {
      expanded.add(categoryId);
    }
    this.expandedCategoryIds.set(expanded);
  }

  isExpanded(categoryId: string): boolean {
    return this.expandedCategoryIds().has(categoryId);
  }

  lookupShareCode(): void {
    const orgId = this.selectedOrganisationId();
    const code = this.shareCode().trim();

    if (!orgId) {
      this.error.set('Choose the organisation before redeeming a share code.');
      return;
    }

    if (!code) {
      this.error.set('Enter a share code generated by the user.');
      return;
    }

    this.loading.set(true);
    this.error.set('');
    this.statusMessage.set('');

    this.api
      .redeemShareCode(orgId, code)
      .pipe(
        catchError((e) => {
          this.error.set(e?.error?.detail ?? 'That share code could not be redeemed.');
          return of(null as ShareCodeRedemptionView | null);
        }),
      )
      .subscribe((result) => {
        this.loading.set(false);

        if (!result) {
          this.redemption.set(null);
          return;
        }

        this.redemption.set(result);

        if (result.status === 'AwaitingApproval') {
          this.statusMessage.set(`Awaiting approval for ${result.fieldCount} field(s). The user must approve the agreement before data is released.`);
          this.approvedRecords.set([]);
          this.beginApprovalPolling(result.userId);
          return;
        }

        this.stopApprovalPolling();
        this.statusMessage.set('The user has approved this request. Live data is now visible below.');
        this.loadApprovedDataForOrganisation();
        this.loadShareRequests();
      });
  }

  private loadShareRequests(): void {
    this.api
      .listOrganisationShareRequests(this.selectedOrganisationId())
      .pipe(catchError(() => of([] as OrganisationShareRequest[])))
      .subscribe((requests) => this.shareRequests.set(Array.isArray(requests) ? requests : []));
  }

  private loadApprovedDataForOrganisation(): void {
    this.api
      .listOrganisationGrants(this.selectedOrganisationId())
      .pipe(catchError(() => of([] as Grant[])))
      .subscribe((grants) => {
        const activeGrants = Array.isArray(grants) ? grants : [];

        if (!activeGrants.length) {
          this.approvedRecords.set([]);
          return;
        }

        forkJoin(
          activeGrants.map((grant) =>
            this.api.getOrganisationCategory(this.selectedOrganisationId(), grant.userId, grant.categoryId).pipe(
              map((category) => this.toSharedRow(grant, category)),
              catchError(() => of(null as SharedDataRow | null)),
            ),
          ),
        ).subscribe((rows) => {
          this.approvedRecords.set(rows.filter((row): row is SharedDataRow => !!row));
        });
      });
  }

  private toSharedRow(grant: Grant, category: OrganisationCategoryValues): SharedDataRow {
    const entries = Object.entries(category.fields ?? {}).map(([fieldId, value]) => ({
      label: category.fieldNames?.[fieldId] ?? `Field ${fieldId.slice(0, 8)}`,
      value: value ?? 'Not shared',
    }));

    return {
      categoryId: grant.categoryId,
      displayName: grant.userDisplayName || grant.userId,
      userId: grant.userId,
      fields: entries.length ? entries : [{ label: 'Status', value: 'Access requested and active' }],
    };
  }
}
